//
//  Graphics.swift
//  LeetTest
//
//  Created by Jim Chuang on 2018/5/22.
//  Copyright © 2018年 jj. All rights reserved.
//

import UIKit

class Graphics: NSObject {
    class func getAddImageNormal() -> UIImage {

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 239, height: 119), false, 1.0)

        //// Color Declarations
        let color = UIColor(red: 1.000, green: 0.000, blue: 1.000, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 0.5, y: 50.5, width: 239, height: 20))
        color.setFill()
        rectanglePath.fill()
        color.setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: 110, y: 0.5, width: 20, height: 119))
        color.setFill()
        rectangle2Path.fill()
        color.setStroke()
        rectangle2Path.lineWidth = 1
        rectangle2Path.stroke()

        //// Star Drawing
        let starPath = UIBezierPath()
        starPath.move(to: CGPoint(x: 36, y: 13.5))
        starPath.addLine(to: CGPoint(x: 40.41, y: 18.9))
        starPath.addLine(to: CGPoint(x: 47.89, y: 20.76))
        starPath.addLine(to: CGPoint(x: 43.13, y: 25.95))
        starPath.addLine(to: CGPoint(x: 43.35, y: 32.49))
        starPath.addLine(to: CGPoint(x: 36, y: 30.3))
        starPath.addLine(to: CGPoint(x: 28.65, y: 32.49))
        starPath.addLine(to: CGPoint(x: 28.87, y: 25.95))
        starPath.addLine(to: CGPoint(x: 24.11, y: 20.76))
        starPath.addLine(to: CGPoint(x: 31.59, y: 18.9))
        starPath.close()
        color.setFill()
        starPath.fill()
        color.setStroke()
        starPath.lineWidth = 1
        starPath.stroke()


        return UIGraphicsGetImageFromCurrentImageContext()!;
    }

    class func getAddImageSelect() -> UIImage {

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 239, height: 119), false, 1.0)

        // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
        // http://www.paintcodeapp.com

        //// Color Declarations
        let color4 = UIColor(red: 0.800, green: 0.320, blue: 0.320, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 0.5, y: 49.5, width: 239, height: 20))
        color4.setFill()
        rectanglePath.fill()
        color4.setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: 110, y: 0.5, width: 20, height: 119))
        color4.setFill()
        rectangle2Path.fill()
        color4.setStroke()
        rectangle2Path.lineWidth = 1
        rectangle2Path.stroke()


        //// Star Drawing
        let starPath = UIBezierPath()
        starPath.move(to: CGPoint(x: 36, y: 13.5))
        starPath.addLine(to: CGPoint(x: 40.41, y: 18.9))
        starPath.addLine(to: CGPoint(x: 47.89, y: 20.76))
        starPath.addLine(to: CGPoint(x: 43.13, y: 25.95))
        starPath.addLine(to: CGPoint(x: 43.35, y: 32.49))
        starPath.addLine(to: CGPoint(x: 36, y: 30.3))
        starPath.addLine(to: CGPoint(x: 28.65, y: 32.49))
        starPath.addLine(to: CGPoint(x: 28.87, y: 25.95))
        starPath.addLine(to: CGPoint(x: 24.11, y: 20.76))
        starPath.addLine(to: CGPoint(x: 31.59, y: 18.9))
        starPath.close()
        color4.setFill()
        starPath.fill()
        color4.setStroke()
        starPath.lineWidth = 1
        starPath.stroke()



        return UIGraphicsGetImageFromCurrentImageContext()!;
    }

}
